// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface StatusPayload {
  running: boolean;
  localIP: string;
  steamID: string;
  peerCount: number;
}

export interface PeerInfo {
  steamID: string;
  ip: string;
}

export function AddPort(arg1: number): Promise<void>;

export function GetAllowedPorts(): Promise<number[]>;

export function GetFirewallState(): Promise<boolean>;

export function GetPeers(): Promise<PeerInfo[]>;

export function GetStatus(): Promise<StatusPayload>;

export function JoinLobby(arg1: number): Promise<void>;

export function RemovePort(arg1: number): Promise<void>;

export function StartBridge(): Promise<void>;

export function StopBridge(): Promise<void>;

export function ToggleFirewall(arg1: boolean): Promise<void>;
