// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPort(arg1:number):Promise<void>;

export function GetAllowedPorts():Promise<Array<number>>;

export function GetFirewallState():Promise<boolean>;

export function GetPeers():Promise<Array<main.PeerInfo>>;

export function GetStatus():Promise<main.StatusPayload>;

export function JoinLobby(arg1:string):Promise<void>;

export function OpenFriendsOverlay():Promise<void>;

export function RemovePort(arg1:number):Promise<void>;

export function StartBridge():Promise<void>;

export function StopBridge():Promise<void>;

export function ToggleFirewall(arg1:boolean):Promise<void>;
