// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPort(arg1) {
  return window['go']['main']['App']['AddPort'](arg1);
}

export function GetAllowedPorts() {
  return window['go']['main']['App']['GetAllowedPorts']();
}

export function GetFirewallState() {
  return window['go']['main']['App']['GetFirewallState']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function JoinLobby(arg1) {
  return window['go']['main']['App']['JoinLobby'](arg1);
}

export function RemovePort(arg1) {
  return window['go']['main']['App']['RemovePort'](arg1);
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}

export function ToggleFirewall(arg1) {
  return window['go']['main']['App']['ToggleFirewall'](arg1);
}
