// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function InitNetwork():Promise<void>;

export function JoinLobby(arg1:number):Promise<void>;
